/* PrepMate interview-focus layer. Keeps the original study library intact. */
(function(){
  var extraCss = '.track-hero{background:linear-gradient(135deg,#151b21,#10151a 60%,#0f1418);border:1px solid #2f3a45;border-radius:10px;padding:18px;margin-bottom:16px}.track-kicker{font:10px var(--mono);letter-spacing:.12em;text-transform:uppercase;color:var(--green);margin-bottom:5px}.track-title{font-size:22px;line-height:1.2;font-weight:800}.track-sub{font-size:12px;color:var(--muted);margin-top:7px}.track-meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:11px}.track-chip{font-size:10px;padding:4px 7px;border:1px solid var(--border);border-radius:999px;background:#11161a;color:var(--muted)}.track-chip.hot{color:var(--green);border-color:#3fb95044}.track-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:9px;margin-top:12px}.next-card,.read-card{background:#10151a;border:1px solid var(--border);border-radius:8px;padding:12px}.next-label,.read-label{font-size:9px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted)}.next-title{font-size:14px;font-weight:700;margin-top:4px}.next-copy,.read-copy{font-size:11px;color:var(--muted);margin-top:4px}.track-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.track-list{display:grid;gap:6px}.track-row{display:grid;grid-template-columns:28px 1fr auto;gap:9px;align-items:center;background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:9px 10px;cursor:pointer}.track-row:hover{border-color:#46515c}.track-no{font:11px var(--mono);color:var(--muted)}.track-row-title{font-size:12px;font-weight:600}.track-row-copy{font-size:10px;color:var(--muted)}.track-row-state{font-size:9px;padding:3px 6px;border-radius:999px;background:var(--s2);color:var(--muted);border:1px solid var(--border)}.track-row-state.hot{color:var(--green);border-color:#3fb95044}@media(max-width:768px){.track-grid{grid-template-columns:1fr}.track-title{font-size:19px}}';
  var st=document.createElement('style');st.textContent=extraCss;document.head.appendChild(st);
  var track=[
    ['java','Java Fundamentals + OOP','JVM, memory, Strings, exceptions, collections, OOP, interfaces and multithreading.'],
    ['java-int','Java Interview Bank','Answer aloud first, then handle the follow-up and trap.'],
    ['dbms','SQL + DBMS','Joins, normalization, ACID, indexes, subqueries and window functions.'],
    ['spring','Spring Boot + REST APIs','DI, IoC, controllers, validation, JPA, transactions, REST and exception handling.'],
    ['project-bank','BankLite Project Defense','Architecture, APIs, database design, transactions, security and trade-offs.'],
    ['project-resolve','ResolveHub Project Defense','REST workflow, JWT, MongoDB, React integration and Gemini failure handling.'],
    ['project-pixel','PixelParadox + AWS','Cloud architecture, deployment, IAM, networking, scaling and observability.'],
    ['patterns','DSA Fundamentals + Coding Approach','Big-O, arrays, strings, hashing, sliding window, two pointers, stacks, trees and graphs.'],
    ['cn','Computer Networks + HTTP','TCP/UDP, DNS, TLS, HTTP status codes, REST, CORS, sockets, routing and NAT.'],
    ['os','Operating Systems Basics','Processes, threads, scheduling, synchronization, deadlock, paging and context switching.'],
    ['git','Git + SDLC + Agile','Branches, commits, PRs, merge/rebase, CI/CD, SDLC phases and Agile ceremonies.'],
    ['hr','HR / Behavioral','Introduction, STAR stories, strengths, weakness, conflict, failure and why Mphasis.'],
    ['mock','Full Mock Interview','Finish with mixed technical practice, project defense and behavioral answers.']
  ];
  var projects={
    'project-bank':{name:'BankLite',stack:'Spring Boot + REST + PostgreSQL',problem:'Banking-style backend for account and transaction operations.',questions:['Why Spring Boot for BankLite?','Why do banking operations need transactions?','How would you prevent concurrent balance corruption?','Why DTOs instead of exposing entities?','How would you secure the APIs?','What indexes would you add and why?']},
    'project-resolve':{name:'ResolveHub',stack:'Node.js + Express + MongoDB + React + JWT + Gemini API',problem:'Apartment maintenance workflow for reporting, assigning and resolving issues.',questions:['Why MongoDB instead of PostgreSQL?','How does JWT authentication work?','Where is input validated?','How do you prevent unauthorized ticket updates?','What happens when Gemini is unavailable?','How would you scale it?']},
    'project-pixel':{name:'PixelParadox',stack:'AWS + web application stack',problem:'A user-facing application deployed with cloud infrastructure.',questions:['Why did you choose those AWS services?','How did you handle IAM and secrets?','How does traffic reach the application?','How would you scale it?','How would you monitor failures?','What would you change for production?']}
  };
  var spring=[
    ['Spring vs Spring Boot','Spring is the broader ecosystem. Spring Boot simplifies setup through starters, auto-configuration and embedded servers.'],
    ['Dependency Injection','Spring supplies dependencies instead of classes constructing them directly. Constructor injection makes dependencies explicit and testable.'],
    ['IoC Container','The container creates, configures and manages beans. Know @Component, @Service, @Repository and @Controller.'],
    ['@RestController','Combines controller behavior with response-body serialization, commonly returning JSON.'],
    ['HTTP methods + status codes','GET reads, POST usually creates, PUT replaces, PATCH partially updates, DELETE removes. Know 200, 201, 204, 400, 401, 403, 404, 409 and 500.'],
    ['DTOs','DTOs define the API contract and avoid exposing persistence internals directly.'],
    ['Validation','Know @Valid, @NotNull, @Size and consistent validation-error responses.'],
    ['Exception handling','Use @ControllerAdvice / @ExceptionHandler for consistent API error responses.'],
    ['JPA basics','Know entities, repositories, lazy loading, N+1, pagination and the persistence context.'],
    ['@Transactional','Defines a transaction boundary. Be ready to explain rollback, propagation and isolation for money-moving operations.'],
    ['REST principles','Use resource-oriented URLs, correct methods/statuses, stateless requests and predictable representations.'],
    ['CORS','A browser-enforced cross-origin policy. The server declares allowed origins, methods and headers.'],
    ['Configuration','Use profiles/environment variables for configuration and secrets instead of hard-coding them.']
  ];
  var git=[
    ['Git fundamentals','Working tree → staging area → commit. Know clone, status, add, commit, pull, push, fetch and log.'],
    ['Branching','Create focused feature branches and keep commits small and meaningful.'],
    ['Merge vs rebase','Merge preserves branch history. Rebase rewrites the branch base into a linear history. Never casually rebase shared history.'],
    ['Pull requests','PRs provide review, discussion, CI checks and a controlled path to main.'],
    ['Conflict resolution','Inspect both sides, resolve intentionally, test, then continue/commit.'],
    ['CI/CD','CI validates changes automatically. CD automates delivery/deployment.'],
    ['SDLC','Requirements → design → implementation → testing → deployment → maintenance.'],
    ['Agile','Know sprint planning, daily stand-up, review/demo and retrospective.'],
    ['SOLID awareness','Be ready to explain SRP and dependency inversion with a small backend example.']
  ];
  function addNav(){
    var groups=[
      {group:'INTERVIEW TRACK',items:[['mphasis','Mphasis Interview Track'],['dashboard','Dashboard']]},
      {group:'CORE CS',items:[['java','Java Fundamentals + OOP'],['dbms','DBMS + SQL'],['os','Operating Systems'],['cn','Networks + HTTP']]},
      {group:'BACKEND',items:[['spring','Spring Boot + REST'],['git','Git + SDLC + Agile']]},
      {group:'PROJECT DEFENSE',items:[['project-bank','BankLite Defense'],['project-resolve','ResolveHub Defense'],['project-pixel','PixelParadox + AWS']]},
      {group:'CODING',items:[['patterns','DSA Patterns'],['dsa','DSA Concepts']]},
      {group:'INTERVIEW BANKS',items:[['java-int','Java Bank'],['dbms-int','DBMS Bank'],['os-int','OS Bank'],['cn-int','Networks Bank'],['dsa-int','DSA Bank'],['hr','HR / Behavioral']]},
      {group:'PRACTICE',items:[['mock','Full Mock Interview'],['mistakes','Mistake Review'],['quickrev','Quick Revision']]},
      {group:'SESSION',items:[['focus','Focus Timer'],['history','Session History']]},
    ];
    SECTIONS.length=0;groups.forEach(function(g){SECTIONS.push({group:g.group,items:g.items.map(function(x){return {id:x[0],label:x[1],cnt:null};})});});
  }
  function topicStatus(section){var ts=TOPICS[section]||[];return ts.length?Math.round(ts.filter(function(t){return Store.getStatus(t.id)==='mastered';}).length/ts.length*100):0;}
  function trackPage(){
    var p=getProgress();var next=p.secs.java<100?'java':p.secs.dbms<100?'dbms':p.secs.cn<100?'cn':'spring';
    var label=(SECTIONS.flatMap(function(g){return g.items;}).find(function(x){return x.id===next;})||{}).label||next;
    var readiness=Math.min(100,Math.round(p.pct*.5+p.patPct*.2+(Store.d.sessions.length?20:0)+(Store.d.mockMistakes.length?10:0)));
    return '<div class="track-hero"><div class="track-kicker">Mphasis interview mode</div><div class="track-title">Study to answer, not just to recognize.</div><div class="track-sub">Follow the sequence top-to-bottom. Read the concept, answer aloud, survive the follow-up, defend your projects, then take the mock.</div><div class="track-meta"><span class="track-chip hot">'+readiness+'% readiness</span><span class="track-chip">Java + OOP first</span><span class="track-chip">Project defense mandatory</span><span class="track-chip">Why / how / trade-off</span></div><div class="track-grid"><div class="next-card"><div class="next-label">Recommended next move</div><div class="next-title">'+esc(label)+'</div><div class="next-copy">Do not jump ahead until you can explain the current topic without reading the answer.</div><div class="track-actions"><button class="btn btn-g" onclick="navigate(\''+next+'\')">Open next →</button><button class="btn" onclick="navigate(\'mock\')">Test me</button></div></div><div class="read-card"><div class="read-label">Interview rule</div><div class="read-copy">Every technical answer should survive one follow-up: “Why?”, “What happens internally?”, or “What trade-off?”</div></div></div></div><div class="sec-h"><h2>13-step interview sequence</h2><p>Use the sidebar for jumping around, but this is the recommended order.</p></div><div class="track-list">'+track.map(function(x,i){return '<div class="track-row" onclick="navigate(\''+x[0]+'\')"><div class="track-no">'+String(i+1).padStart(2,'0')+'</div><div><div class="track-row-title">'+esc(x[1])+'</div><div class="track-row-copy">'+esc(x[2])+'</div></div><div class="track-row-state '+(i<2?'hot':'')+'">'+(i<2?'START':'NEXT')+'</div></div>';}).join('')+'</div>';
  }
  function cards(title,sub,arr){return '<div class="sec-h"><h2>'+title+'</h2><p>'+sub+'</p></div>'+arr.map(function(x,i){return '<div class="int-item"><div class="int-q" onclick="this.parentElement.classList.toggle(\'open\')"><span>'+esc(x[0])+'</span><span class="int-chev">▶</span></div><div class="int-bd"><div class="int-f"><div class="int-f-l">Interview Answer</div><div class="int-f-v">'+esc(x[1])+'</div></div><div class="int-trap">⚠ Follow-up: connect this concept to a real project.</div></div></div>';}).join('');}
  function projectPage(id){var p=projects[id];return '<div class="sec-h"><h2>'+esc(p.name)+' Project Defense</h2><p>'+esc(p.stack)+' · Defend what you actually built. Never invent details.</p></div><div class="proj-ed"><h3>Defense worksheet</h3><div class="fg"><div class="ff"><label class="fl">Project Name</label><input class="fi" id="px-name" value="'+esc(p.name)+'"></div><div class="ff"><label class="fl">Tech Stack</label><input class="fi" id="px-stack" value="'+esc(p.stack)+'"></div><div class="ff full"><label class="fl">Problem Solved</label><textarea class="fi" id="px-problem" rows="2">'+esc(p.problem)+'</textarea></div><div class="ff full"><label class="fl">Architecture</label><textarea class="fi" id="px-arch" rows="2" placeholder="Draw the real flow here..."></textarea></div><div class="ff full"><label class="fl">My Exact Contribution</label><textarea class="fi" id="px-contrib" rows="2"></textarea></div><div class="ff"><label class="fl">Hardest Bug / Challenge</label><textarea class="fi" id="px-chal" rows="2"></textarea></div><div class="ff"><label class="fl">Key Tradeoff</label><textarea class="fi" id="px-trade" rows="2"></textarea></div><div class="ff full"><label class="fl">What I Would Improve</label><textarea class="fi" id="px-future" rows="2"></textarea></div></div><div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:10px"><button class="btn btn-g" onclick="projectSave()">Save</button><button class="btn" onclick="projectPitch(\''+id+'\')">Generate 90-sec Pitch</button></div><div class="pitch-out" id="px-out"></div></div><div class="sec-h" style="margin-top:16px"><h2>Likely interviewer questions</h2></div>'+p.questions.map(function(q){return '<div class="int-item"><div class="int-q" onclick="this.parentElement.classList.toggle(\'open\')"><span>'+esc(q)+'</span><span class="int-chev">▶</span></div><div class="int-bd"><div class="int-f"><div class="int-f-l">Answer shape</div><div class="int-f-v">Start with the actual implementation, then explain why, the trade-off, and one improvement.</div></div></div></div>';}).join('');}
  window.projectSave=function(){var f=function(k){return document.getElementById(k)?.value||'';};localStorage.setItem('prepmate-interview-project-'+State.section,JSON.stringify({name:f('px-name'),stack:f('px-stack'),problem:f('px-problem'),arch:f('px-arch'),contribution:f('px-contrib'),challenges:f('px-chal'),tradeoffs:f('px-trade'),future:f('px-future')}));toast('Project defense saved');};
  window.projectPitch=function(id){projectSave();var d=JSON.parse(localStorage.getItem('prepmate-interview-project-'+State.section)||'{}');var p=projects[id];var out='PROJECT: '+(d.name||p.name)+'\nSTACK: '+(d.stack||p.stack)+'\n\nProblem: '+d.problem+'\n\nArchitecture: '+d.arch+'\n\nMy contribution: '+d.contribution+'\n\nHardest challenge: '+d.challenges+'\n\nTrade-off: '+d.tradeoffs+'\n\nImprovement: '+d.future;document.getElementById('px-out').textContent=out;document.getElementById('px-out').classList.add('show');};
  window.renderMain=function(){var mc=document.getElementById('mainContent');var wrap=function(s){return '<div class="content">'+s+'</div>';};var sec=State.section;if(State.query){mc.innerHTML=wrap(renderSearch(State.query));return;}if(sec==='mphasis'){mc.innerHTML=wrap(trackPage());return;}if(sec==='spring'){mc.innerHTML=wrap(cards('Spring Boot + REST APIs','Read each answer, close it, then explain it yourself.',spring));return;}if(sec==='git'){mc.innerHTML=wrap(cards('Git + SDLC + Agile','Explain workflow, not commands.',git));return;}if(sec.indexOf('project-')===0){mc.innerHTML=wrap(projectPage(sec));return;}if(sec==='dashboard'){mc.innerHTML=wrap(renderDashboard());return;}if(TOPICS[sec]){mc.innerHTML=wrap(renderTopics(sec));return;}if(sec==='patterns'){mc.innerHTML=wrap(renderPatterns());return;}if(sec==='quant'||sec==='logical'||sec==='verbal'){mc.innerHTML=wrap(renderAptitude(sec));return;}if(sec==='java-int'||sec==='dbms-int'||sec==='os-int'||sec==='cn-int'||sec==='dsa-int'){mc.innerHTML=wrap(renderInterviewBank(sec.replace('-int','')));return;}if(sec==='hr'){mc.innerHTML=wrap(renderHR());return;}if(sec==='mock'){mc.innerHTML=wrap(renderMockSetup());return;}if(sec==='mistakes'){mc.innerHTML=wrap(renderMistakes());return;}if(sec==='quickrev'){mc.innerHTML=wrap(renderQuickRev());return;}if(sec==='focus'){mc.innerHTML=wrap(renderFocus());return;}if(sec==='history'){mc.innerHTML=wrap(renderHistory());return;}mc.innerHTML=wrap('<div class="empty">Section not found.</div>');};
  addNav();
  var oldBrand=document.querySelector('.brand-sub');if(oldBrand)oldBrand.textContent='Mphasis Interview OS';
  var oldProg=document.querySelector('.sb-prog-lbl span');if(oldProg)oldProg.textContent='Interview readiness';
  navigate('mphasis');
})();